server:
  port: 9992
spring:
  application:
    name: API-SEARCH
  cloud:
    nacos:
      server-addr: 192.168.108.130:8848
  rabbitmq:
    host: 192.168.108.130
    port: 5672
    username: admin
    password: admin
    virtual-host: /

elasticsearch.host: 192.168.108.130:9200

